/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_rangga_17111246_cid17b;

import java.awt.Dialog;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangga
 */
public class Menu extends javax.swing.JFrame {
    
    // deklarasi
    Connection con;
    Statement stat;
    PreparedStatement pst = null;
    ResultSet rs;
    String sql;
    String auto_nik;

    /**
     * Creates new form Menu
     * @throws java.io.IOException
     */
    public Menu() throws IOException {
        initComponents();
        ConnectionDb DB = new ConnectionDb();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        pst = DB.pst;
        frmKaryawan.setVisible(false);
        frmKaryawan.setEnabled(false);
        frmBarang.setVisible(false);
        frmBarang.setEnabled(false);
        getDataKaryawan("get all");
        getDataItem("get all");
//        SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd 'at' HH:mm:ss z");
        SimpleDateFormat formatter= new SimpleDateFormat("dd-MMM-YYYY");
        Date date = new Date(System.currentTimeMillis());
        lblCurrentDate.setText(formatter.format(date));
        setDefaultBtnKaryawan();
        showComboJenisItem();
        showComboSupplier();
        setDefaultBtnItem();
        String abc = "1.PT GARUDA";
        String[] dd = abc.split("\\.");
        System.out.println(dd[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        frmKaryawan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNik = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jDateOfBirth = new com.toedter.calendar.JDateChooser();
        cmbRole = new javax.swing.JComboBox<>();
        btnDeleteKry = new javax.swing.JButton();
        btnUpdateKry = new javax.swing.JButton();
        btnSaveKry = new javax.swing.JButton();
        btnKaryawanNew = new javax.swing.JToggleButton();
        txtNik = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnExitKaryawan = new javax.swing.JButton();
        txtSearchKaryawan = new javax.swing.JTextField();
        btnPrintKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        frmBarang = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblSupplier = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblDateOfBirth1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        txtBarcodeItem = new javax.swing.JTextField();
        txtNameItem = new javax.swing.JTextField();
        txtPriceSaleItem = new javax.swing.JTextField();
        cmbSupplier = new javax.swing.JComboBox<>();
        btnDeleteItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        btnSaveItem = new javax.swing.JButton();
        txtPriceBuyItem = new javax.swing.JTextField();
        txtPluItem = new javax.swing.JTextField();
        cbmJenisItem = new javax.swing.JComboBox<>();
        btnNewItem = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnExitKaryawan1 = new javax.swing.JButton();
        txtSearchItem = new javax.swing.JTextField();
        btnPrintKaryawan1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCurrentDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMaster = new javax.swing.JMenu();
        mnitmKaryawan = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventori Barang V 0.1.0");
        setLocationByPlatform(true);

        jPanel2.setBackground(new java.awt.Color(170, 163, 163));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        frmKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Karyawan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        frmKaryawan.setEnabled(false);
        frmKaryawan.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        lblNik.setText("NIK");

        lblName.setText("NAMA");

        lblUsername.setText("USERNAME");

        lblDateOfBirth.setText("TGL LAHIR");

        lblPhone.setText("NO HP");

        lblAddress.setText("ALAMAT");

        lblRole.setText("ROLE");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "ADMIN", "USER" }));

        btnDeleteKry.setText("HAPUS");
        btnDeleteKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKryActionPerformed(evt);
            }
        });

        btnUpdateKry.setText("EDIT");
        btnUpdateKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKryActionPerformed(evt);
            }
        });

        btnSaveKry.setText("SIMPAN");
        btnSaveKry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveKryActionPerformed(evt);
            }
        });

        btnKaryawanNew.setText("BARU");
        btnKaryawanNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanNewActionPerformed(evt);
            }
        });

        txtNik.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDateOfBirth)
                                .addGap(18, 18, 18)
                                .addComponent(jDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPhone)
                                .addGap(39, 39, 39)
                                .addComponent(txtPhone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddress)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateKry, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnKaryawanNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteKry, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(btnSaveKry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNik)
                                    .addComponent(lblName))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNik))))
                        .addGap(55, 55, 55)
                        .addComponent(lblRole)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNik)
                                .addComponent(txtNik))
                            .addComponent(lblRole))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateOfBirth)
                            .addComponent(jDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveKry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKaryawanNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateKry, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnDeleteKry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAddress)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKaryawan);

        btnExitKaryawan.setText("KELUAR");
        btnExitKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitKaryawanActionPerformed(evt);
            }
        });

        txtSearchKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKaryawanKeyPressed(evt);
            }
        });

        btnPrintKaryawan.setText("PRINT");

        jLabel1.setText("CARI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPrintKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExitKaryawan)
                    .addComponent(btnPrintKaryawan))
                .addContainerGap())
        );

        javax.swing.GroupLayout frmKaryawanLayout = new javax.swing.GroupLayout(frmKaryawan);
        frmKaryawan.setLayout(frmKaryawanLayout);
        frmKaryawanLayout.setHorizontalGroup(
            frmKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frmKaryawanLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frmKaryawanLayout.setVerticalGroup(
            frmKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmKaryawanLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleParent(this);

        frmBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Barang", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        frmBarang.setEnabled(false);
        frmBarang.setFocusable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        lblSupplier.setText("SUPPLIER");

        lblJenis.setText("JENIS");

        lblItemName.setText("NAMA");

        lblDateOfBirth1.setText("HARGA BELI");

        lblPhone1.setText("HARGA JUAL");

        lblAddress1.setText("BARCODE");

        lblRole1.setText("PLU");

        btnDeleteItem.setText("HAPUS");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnUpdateItem.setText("EDIT");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        btnSaveItem.setText("SIMPAN");
        btnSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveItemActionPerformed(evt);
            }
        });

        btnNewItem.setText("BARU");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplier)
                            .addComponent(lblJenis)
                            .addComponent(lblItemName)
                            .addComponent(lblDateOfBirth1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtPriceBuyItem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbSupplier, 0, 212, Short.MAX_VALUE)
                                    .addComponent(cbmJenisItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress1)
                                    .addComponent(lblRole1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBarcodeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txtPluItem)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhone1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPriceSaleItem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(btnNewItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSupplier)
                        .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRole1)
                    .addComponent(txtPluItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtBarcodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPriceSaleItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblJenis))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblAddress1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbmJenisItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblItemName)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceBuyItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDateOfBirth1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone1)
                                    .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveItem, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnNewItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblItem);

        btnExitKaryawan1.setText("KELUAR");
        btnExitKaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitKaryawan1ActionPerformed(evt);
            }
        });

        btnPrintKaryawan1.setText("PRINT");

        jLabel3.setText("CARI");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(btnPrintKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExitKaryawan1)
                    .addComponent(btnPrintKaryawan1))
                .addContainerGap())
        );

        javax.swing.GroupLayout frmBarangLayout = new javax.swing.GroupLayout(frmBarang);
        frmBarang.setLayout(frmBarangLayout);
        frmBarangLayout.setHorizontalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frmBarangLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        frmBarangLayout.setVerticalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBarangLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frmKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frmKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCurrentDate.setText("jLabel1");

        jLabel2.setText("Tanggal:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentDate)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentDate)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        mnMaster.setText("Master Data");

        mnitmKaryawan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mnitmKaryawan.setText("Karyawan");
        mnitmKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmKaryawanActionPerformed(evt);
            }
        });
        mnMaster.add(mnitmKaryawan);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Supplier");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Barang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Jenis Barang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem3);

        jMenuBar1.add(mnMaster);

        mnTransaksi.setText("Transaksi");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Barang Masuk");
        mnTransaksi.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Barang Keluar");
        mnTransaksi.add(jMenuItem5);

        jMenuBar1.add(mnTransaksi);

        mnLaporan.setText("Laporan");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Data Barang");
        mnLaporan.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Pemasukan Barang");
        mnLaporan.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Pengluaran Barang");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem8);

        jMenuBar1.add(mnLaporan);

        mnExit.setText("Exit");
        mnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitmKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmKaryawanActionPerformed
        // TODO add your handling code here:
        frmKaryawan.setVisible(true);
        SimpleDateFormat formatter= new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date(System.currentTimeMillis());
        System.out.println(formatter.format(date));
        lblCurrentDate.setText(formatter.format(date));
        frmKaryawan.setEnabled(true);
        getDataKaryawan("get all");
    }//GEN-LAST:event_mnitmKaryawanActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnExitKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitKaryawanActionPerformed
        // TODO add your handling code here:
        frmKaryawan.setVisible(false);
        frmKaryawan.setEnabled(false);
        setDefaultBtnKaryawan();
    }//GEN-LAST:event_btnExitKaryawanActionPerformed

    private void btnExitKaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitKaryawan1ActionPerformed
        // TODO add your handling code here:
        frmBarang.setVisible(false);
        frmBarang.setEnabled(false);
    }//GEN-LAST:event_btnExitKaryawan1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmBarang.setVisible(true);
        frmBarang.setEnabled(true);
        getDataItem("get all");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            Supplier S = new Supplier();
            S.setVisible(true);
            S.setExtendedState(Supplier.MAXIMIZED_BOTH);
            S.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            S.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            TypeItem T = new TypeItem();
            T.setVisible(true);
            T.setAlwaysOnTop(true);
            T.setLocationRelativeTo(this);
            T.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            T.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtSearchKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKaryawanKeyPressed
        // TODO add your handling code here:
        getDataKaryawan("search");
    }//GEN-LAST:event_txtSearchKaryawanKeyPressed

    private void btnKaryawanNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanNewActionPerformed
        // TODO add your handling code here:
        AutoNik();
        btnSaveKry.setEnabled(true);
    }//GEN-LAST:event_btnKaryawanNewActionPerformed

    private void btnSaveKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveKryActionPerformed
        if( txtName.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nama Harus diisi!");
            }else if("".equals(txtNik.getText())){
                JOptionPane.showMessageDialog(null, "Nik Harus diisi!");
            }else if("".equals( txtUsername.getText())){
                JOptionPane.showMessageDialog(null, "Username Harus diisi!");
            }else if("".equals( txtUsername.getText())){
                JOptionPane.showMessageDialog(null, "Password Harus diisi!");
            }else if( jDateOfBirth.getDate() == null){
                JOptionPane.showMessageDialog(null, "Tanggal Lahir Harus diisi!");
            }else if("".equals(txtPhone.getText())){
                JOptionPane.showMessageDialog(null, "No Hp Harus diisi!");
            }else if("".equals(txtAddress.getText())){
                JOptionPane.showMessageDialog(null, "Alamat Harus diisi!");
            }else if("-".equals(cmbRole.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Role Harus diisi!");
            }else{
        try {
            java.util.Date TglLahir = jDateOfBirth.getDate();
            java.sql.Date sqldate = new java.sql.Date(TglLahir.getTime());
            User user = new User();
            user.nik = txtNik.getText();
            user.name = txtName.getText();
            user.username = txtUsername.getText();
            user.password = txtUsername.getText();
            user.birth_of_date = sqldate;
            user.phone = txtPhone.getText();
            user.address = txtAddress.getText();
            user.role = (String) cmbRole.getSelectedItem();
            user.transactionUsers("save");
            getDataKaryawan("get all");
            setNullValue();
            setDefaultBtnKaryawan();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_btnSaveKryActionPerformed

    private void btnDeleteKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKryActionPerformed
       int selRow = tblKaryawan.getSelectedRow();
       String  nik = tblKaryawan.getValueAt(selRow, 0).toString();
       try {
            User user = new User();
            user.nik = nik;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Anda yakin untuk hapus karyawan tersebut?");
            if(dialogResult == JOptionPane.YES_OPTION){
                 user.transactionUsers("delete");
                 setDefaultBtnKaryawan();
                 setNullValue();
                 getDataKaryawan("get all");
            }
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteKryActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
         int selRow = tblKaryawan.getSelectedRow();
        String  nik = tblKaryawan.getValueAt(selRow, 0).toString();
        String  name = tblKaryawan.getValueAt(selRow, 1).toString();
        String  username = tblKaryawan.getValueAt(selRow, 2).toString();
        String  phone = tblKaryawan.getValueAt(selRow, 4).toString();
        String  address = tblKaryawan.getValueAt(selRow, 5).toString();
        String  role = tblKaryawan.getValueAt(selRow, 6).toString();
        txtNik.setText(nik);
        txtName.setText(name);
        txtUsername.setText(username);
        txtPhone.setText(phone);
        txtAddress.setText(address);
        cmbRole.setSelectedItem(role);
        try{
            sql = "SELECT birth_of_date as dob from `users` ";
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
           rs.next();
           jDateOfBirth.setDate(rs.getDate("dob"));
        } catch(SQLException  e){ 
            JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
        btnUpdateKry.setEnabled(true);
        btnDeleteKry.setEnabled(true);
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void btnUpdateKryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKryActionPerformed
        try {
            java.util.Date TglLahir = jDateOfBirth.getDate();
            java.sql.Date sqldate = new java.sql.Date(TglLahir.getTime());
            User user = new User();
            user.nik = txtNik.getText();
            user.name = txtName.getText();
            user.username = txtUsername.getText();
            user.birth_of_date = sqldate;
            user.phone = txtPhone.getText();
            user.address = txtAddress.getText();
            user.role = (String) cmbRole.getSelectedItem();
            
            int dialogResult = JOptionPane.showConfirmDialog (this, "Anda yakin untuk edit karyawan tersebut?");
            if(dialogResult == JOptionPane.YES_OPTION){
                 user.transactionUsers("update");
                 getDataKaryawan("get all");
                 setNullValue();
                 setDefaultBtnKaryawan();
            }
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateKryActionPerformed

    private void btnSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveItemActionPerformed
        // TODO add your handling code here:
         if( txtNameItem.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nama Harus diisi!");
            }else if("-".equals(cmbSupplier.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Supplier Harus diisi!");
            }else if("-".equals( cbmJenisItem.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Jenis Harus diisi!");
            }else if("".equals( txtPriceBuyItem.getText())){
                JOptionPane.showMessageDialog(null, "Harga Beli Harus diisi!");
            }else if( txtPriceSaleItem.getText() == null){
                JOptionPane.showMessageDialog(null, "Harga Jual Lahir Harus diisi!");
            }else if("".equals(txtBarcodeItem.getText())){
                JOptionPane.showMessageDialog(null, "Barcode Harus diisi!");
            }else if("-".equals(txtPluItem.getText())){
                JOptionPane.showMessageDialog(null, "Plu Harus diisi!");
            }else{
        try {
            String sup_id = (String) cmbSupplier.getSelectedItem();
            String[] sup_id2 = sup_id.split("\\.");
            String Supplier_id = sup_id2[0];
            String j_id = (String) cbmJenisItem.getSelectedItem();
            String[] j_id2 = j_id.split("\\.");
            String Jenis_id = j_id2[0];
            ModelItem item = new ModelItem();
            item.supplier_id = Supplier_id;
            item.type_item_id =Jenis_id;
            item.name = txtNameItem.getText();
            item.price_buy = Integer.parseInt(txtPriceBuyItem.getText());
            item.price_sale = Integer.parseInt(txtPriceSaleItem.getText());
            item.barcode = txtBarcodeItem.getText();
            item.plu = txtPluItem.getText();
            item.transactions("save");
            getDataItem("get all");
            setNullValueItem();
            setDefaultBtnItem();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_btnSaveItemActionPerformed

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        // TODO add your handling code here:
       btnSaveItem.setEnabled(true);
       btnUpdateItem.setEnabled(false);
       btnDeleteItem.setEnabled(false);
    }//GEN-LAST:event_btnNewItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int selRow = tblItem.getSelectedRow();
       String  id = tblItem.getValueAt(selRow, 0).toString();
       try {
             ModelItem item = new ModelItem();
            item.id = id;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Anda yakin untuk hapus Barang tersebut?");
            if(dialogResult == JOptionPane.YES_OPTION){
                 item.transactions("delete");
                 getDataItem("get all");
                setNullValueItem();
                setDefaultBtnItem();
            }
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        int selRow = tblItem.getSelectedRow();
       String  id = tblItem.getValueAt(selRow, 0).toString();
       try{
            sql = "SELECT i.id as id, s.id as sid, s.name as supplier, t.id as tid, t.name as jenis, i.name, i.price_buy, i.price_sale, i.stock, i.barcode, i.plu FROM item i JOIN supplier s on i.supplier_id = s.id JOIN type_item t ON i.type_item_id = t.id WHERE i.id ="+id+";";
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            cmbSupplier.setSelectedItem(rs.getString("sid")+"."+rs.getString("supplier"));
            cbmJenisItem.setSelectedItem(rs.getString("tid")+"."+rs.getString("jenis"));
            txtNameItem.setText(rs.getString("name"));
            txtPriceBuyItem.setText(rs.getString("price_buy"));
            txtPriceSaleItem.setText( rs.getString("price_sale"));       
            txtBarcodeItem.setText(rs.getString("barcode"));        
            txtPluItem.setText(rs.getString("plu"));        
              
        } catch(SQLException  e){ 
            JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
        btnDeleteItem.setEnabled(true);
        btnUpdateItem.setEnabled(true);
    }//GEN-LAST:event_tblItemMouseClicked

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        // TODO add your handling code here:
        if( txtNameItem.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nama Harus diisi!");
            }else if("-".equals(cmbSupplier.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Supplier Harus diisi!");
            }else if("-".equals( cbmJenisItem.getSelectedItem())){
                JOptionPane.showMessageDialog(null, "Jenis Harus diisi!");
            }else if("".equals( txtPriceBuyItem.getText())){
                JOptionPane.showMessageDialog(null, "Harga Beli Harus diisi!");
            }else if( txtPriceSaleItem.getText() == null){
                JOptionPane.showMessageDialog(null, "Harga Jual Lahir Harus diisi!");
            }else if("".equals(txtBarcodeItem.getText())){
                JOptionPane.showMessageDialog(null, "Barcode Harus diisi!");
            }else if("-".equals(txtPluItem.getText())){
                JOptionPane.showMessageDialog(null, "Plu Harus diisi!");
            }else{
        try {
            int selRow = tblItem.getSelectedRow();
            String  id = tblItem.getValueAt(selRow, 0).toString();
            String sup_id = (String) cmbSupplier.getSelectedItem();
            String[] sup_id2 = sup_id.split("\\.");
            String Supplier_id = sup_id2[0];
            String j_id = (String) cbmJenisItem.getSelectedItem();
            String[] j_id2 = j_id.split("\\.");
            String Jenis_id = j_id2[0];
            ModelItem item = new ModelItem();
            item.id = id;
            item.supplier_id = Supplier_id;
            item.type_item_id =Jenis_id;
            item.name = txtNameItem.getText();
            item.price_buy = Integer.parseInt(txtPriceBuyItem.getText());
            item.price_sale = Integer.parseInt(txtPriceSaleItem.getText());
            item.barcode = txtBarcodeItem.getText();
            item.plu = txtPluItem.getText();
            item.transactions("update");
            getDataItem("get all");
            setNullValueItem();
            setDefaultBtnItem();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void mnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitMouseClicked
    
    private void setNullValueItem(){
        cmbSupplier.setSelectedItem("-");
        cbmJenisItem.setSelectedItem("-");
        txtNameItem.setText(null);
        txtPriceBuyItem.setText(null);
        txtPriceSaleItem.setText(null);
        txtBarcodeItem.setText(null);
        txtPluItem.setText(null);
    }
    
    private void AutoNik(){
        SimpleDateFormat formatter= new SimpleDateFormat("yy");
        SimpleDateFormat formatMonth= new SimpleDateFormat("MM");
        Date date = new Date(System.currentTimeMillis());
        String year = formatter.format(date);
        String month = formatMonth.format(date);
        String year_month = year+month;
        String nik;
        String tmp;
        String result_nik;
        String number;
        try{
            sql = "SELECT max(nik) as nik from `users` ";
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
           rs.next();
               nik =  rs.getString("nik");
               System.out.println(nik);
               if(nik != null){
                   tmp = nik.substring(0, 4);
                   if(tmp .equals(year_month)){
                       Integer a =  Integer.parseInt(nik)+1;
                       number = a.toString();
                       result_nik =number;                       
                   }else{
                       result_nik = year_month+"0001";
                   }                   
               }else{
                   result_nik = year_month+"0001";
               }
               auto_nik = result_nik;
               txtNik.setText(auto_nik);
              
        } catch(SQLException  e){ 
            JOptionPane.showMessageDialog(this, e.getMessage()); 
        }
    }
    
    private void setDefaultBtnKaryawan(){
        btnSaveKry.setEnabled(false);
        btnUpdateKry.setEnabled(false);
        btnDeleteKry.setEnabled(false);
    }
    
    private void setNullValue(){
             txtNik.setText("-");
             txtName.setText(null);
             txtUsername.setText(null);
             txtUsername.setText(null);
             txtPhone.setText(null);
             txtAddress.setText(null);
             cmbRole.setSelectedIndex(0);
             jDateOfBirth.setDate(null);
    }
    
    private void getDataItem(String type){
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("ID");
        tb.addColumn("SUPPLIER");
        tb.addColumn("JENIS");
        tb.addColumn("NAMA");
        tb.addColumn("HARGA BELI");
        tb.addColumn("HARGA JUAL");
        tb.addColumn("STOK");
        tb.addColumn("BARCODE");
        tb.addColumn("PLU");
        tblItem.setModel(tb);
        try{
            if("search".equals(type)){
                sql = "SELECT i.id as id, s.id as sid, s.name as supplier, t.id as tid, t.name as jenis, i.name, i.price_buy, i.price_sale, i.stock, i.barcode, i.plu FROM item i JOIN supplier s on i.supplier_id = s.id JOIN type_item t ON i.type_item_id = t.id WHERE concat(i.name, i.barcode, i.plu) like '%"+txtSearchItem.getText()+"%'";
            }else{
                sql = "SELECT i.id as id, s.id as sid, s.name as supplier, t.id as tid, t.name as jenis, i.name, i.price_buy, i.price_sale, i.stock, i.barcode, i.plu FROM item i JOIN supplier s on i.supplier_id = s.id JOIN type_item t ON i.type_item_id = t.id";
            }
            
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("supplier"),
                    rs.getString("jenis"),
                    rs.getString("name"),
                    rs.getString("price_buy"),
                    rs.getString("price_sale"),
                    rs.getString("stock"),
                    rs.getString("barcode"),
                    rs.getString("plu")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void setDefaultBtnItem(){
        btnUpdateItem.setEnabled(false);
        btnDeleteItem.setEnabled(false);
        btnSaveItem.setEnabled(false);
    }
    
    private void getDataKaryawan(String type){
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("NIK");
        tb.addColumn("NAMA");
        tb.addColumn("USERNAME");
        tb.addColumn("TGL LAHIR");
        tb.addColumn("NO HP");
        tb.addColumn("ALAMAT");
        tb.addColumn("ROLE");
        tblKaryawan.setModel(tb);
        try{
            if("search".equals(type)){
                sql = "SELECT * FROM `users` WHERE concat(`name`) like '%"+txtSearchKaryawan.getText()+"%'";
            }else{
                sql = "SELECT * FROM users";
            }
            
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("nik"),
                    rs.getString("name"),
                    rs.getString("username"),
                    rs.getString("birth_of_date"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("role")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void showComboSupplier(){
        try {
            sql = "SELECT * FROM `supplier`";
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            cmbSupplier.addItem("-");
            while(rs.next()){
                cmbSupplier.addItem(rs.getString("id")+"."+rs.getString("name"));
            }
            
        } catch  (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void showComboJenisItem(){
        try {
            sql = "SELECT * FROM `type_item`";
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            cbmJenisItem.addItem("-");
            while(rs.next()){
                cbmJenisItem.addItem(rs.getString("id")+"."+rs.getString("name"));
            }
            
        } catch  (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDeleteKry;
    private javax.swing.JButton btnExitKaryawan;
    private javax.swing.JButton btnExitKaryawan1;
    private javax.swing.JToggleButton btnKaryawanNew;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JButton btnPrintKaryawan;
    private javax.swing.JButton btnPrintKaryawan1;
    private javax.swing.JButton btnSaveItem;
    private javax.swing.JButton btnSaveKry;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnUpdateKry;
    private javax.swing.JComboBox<String> cbmJenisItem;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JPanel frmBarang;
    private javax.swing.JPanel frmKaryawan;
    private com.toedter.calendar.JDateChooser jDateOfBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblCurrentDate;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDateOfBirth1;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu mnExit;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenuItem mnitmKaryawan;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBarcodeItem;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameItem;
    private javax.swing.JLabel txtNik;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPluItem;
    private javax.swing.JTextField txtPriceBuyItem;
    private javax.swing.JTextField txtPriceSaleItem;
    private javax.swing.JTextField txtSearchItem;
    private javax.swing.JTextField txtSearchKaryawan;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
