/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_rangga_17111246_cid17b;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangga
 */
public class Supplier extends javax.swing.JFrame {
    
    // deklarasi
    Connection con;
    Statement stat;
    PreparedStatement pst = null;
    ResultSet rs;
    String sql;
    String id_supplier;

    /**
     * Creates new form Supplier
     * @throws java.io.IOException
     */
    public Supplier() throws IOException {
        initComponents();
        ConnectionDb DB = new ConnectionDb();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        pst = DB.pst;
        getDataSupplier("get_all");
        setDefaultBtn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSupplierName = new javax.swing.JLabel();
        lblSupplierPhone = new javax.swing.JLabel();
        lblSupplierAddress = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSupplierAddress = new javax.swing.JTextArea();
        txtSupplierName = new javax.swing.JTextField();
        btnSupplierSave = new javax.swing.JToggleButton();
        btnSupplierEdit = new javax.swing.JToggleButton();
        btnSupplierDelete = new javax.swing.JToggleButton();
        btnSupplierNew = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        txtSupplierSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        btnSupplierPrint = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vSupplierPhone = new javax.swing.JLabel();
        vSupplierName = new javax.swing.JLabel();
        vSupplierAddress = new javax.swing.JLabel();

        setTitle("Supplier");
        setBackground(new java.awt.Color(151, 149, 149));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        lblSupplierName.setText("NAMA");

        lblSupplierPhone.setText("TELEPON");

        lblSupplierAddress.setText("ALAMAT");

        txtSupplierAddress.setColumns(20);
        txtSupplierAddress.setRows(5);
        txtSupplierAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtSupplierAddress);

        btnSupplierSave.setText("SIMPAN");
        btnSupplierSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierSaveActionPerformed(evt);
            }
        });

        btnSupplierEdit.setText("EDIT");
        btnSupplierEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierEditActionPerformed(evt);
            }
        });

        btnSupplierDelete.setText("DELETE");
        btnSupplierDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDeleteActionPerformed(evt);
            }
        });

        btnSupplierNew.setText("BARU");
        btnSupplierNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierPhone)
                            .addComponent(lblSupplierAddress)
                            .addComponent(lblSupplierName))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtSupplierName)
                            .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupplierNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSupplierSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(btnSupplierDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierName)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierPhone)
                    .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSupplierAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplierSave)
                    .addComponent(btnSupplierEdit)
                    .addComponent(btnSupplierDelete)
                    .addComponent(btnSupplierNew))
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        txtSupplierSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierSearchKeyPressed(evt);
            }
        });

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        btnSupplierPrint.setText("PRINT");

        jLabel4.setText("CARI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSupplierSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSupplierPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnSupplierPrint)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));

        jLabel1.setText("NAMA");

        jLabel2.setText("TELEPON");

        jLabel3.setText("ALAMAT");

        vSupplierPhone.setText("-");

        vSupplierName.setText("-");

        vSupplierAddress.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vSupplierAddress)
                    .addComponent(vSupplierName)
                    .addComponent(vSupplierPhone))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vSupplierName))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vSupplierPhone))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vSupplierAddress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierSaveActionPerformed
        // TODO add your handling code here:
        transactionSupplier("save");
        clearForm();
        getDataSupplier("get_all");
    }//GEN-LAST:event_btnSupplierSaveActionPerformed

    private void txtSupplierSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierSearchKeyPressed
        // TODO add your handling code here:
        getDataSupplier("search");
    }//GEN-LAST:event_txtSupplierSearchKeyPressed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        // TODO add your handling code here:
         int selRow = tblSupplier.getSelectedRow();
         Object id = tblSupplier.getValueAt(selRow, 0);
         Object name = tblSupplier.getValueAt(selRow, 1);
         Object phone = tblSupplier.getValueAt(selRow, 2);
         Object address = tblSupplier.getValueAt(selRow, 3);
         
         id_supplier = id.toString();
         txtSupplierName.setText(name.toString());
         txtSupplierPhone.setText(phone.toString());
         txtSupplierAddress.setText(address.toString());
         
         vSupplierName.setText(name.toString());
         vSupplierPhone.setText(phone.toString());
         vSupplierAddress.setText(address.toString());
         
         txtSupplierName.setEnabled(true);
        txtSupplierPhone.setEnabled(true);
        txtSupplierAddress.setEnabled(true);
         btnSupplierEdit.setEnabled(true);
         btnSupplierDelete.setEnabled(true);
         btnSupplierSave.setEnabled(false);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnSupplierNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierNewActionPerformed
        // TODO add your handling code here:
        clearForm();
        btnSupplierEdit.setEnabled(false);
        btnSupplierDelete.setEnabled(false);
        btnSupplierSave.setEnabled(true);
        txtSupplierName.setEnabled(true);
        txtSupplierPhone.setEnabled(true);
        txtSupplierAddress.setEnabled(true);
        clearVlabel();
        
    }//GEN-LAST:event_btnSupplierNewActionPerformed

    private void btnSupplierEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierEditActionPerformed
        // TODO add your handling code here:
        transactionSupplier("update");
        clearForm();
        getDataSupplier("get_all");
    }//GEN-LAST:event_btnSupplierEditActionPerformed

    private void btnSupplierDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDeleteActionPerformed
        // TODO add your handling code here:
        transactionSupplier("delete");
        clearForm();
        getDataSupplier("get_all");
        clearVlabel();
        setDefaultBtn();
    }//GEN-LAST:event_btnSupplierDeleteActionPerformed
    
    private void getDataSupplier(String type){
        DefaultTableModel tb= new DefaultTableModel();
        tb.addColumn("SUPPLIER ID");
        tb.addColumn("NAMA");
        tb.addColumn("TELEPON");
        tb.addColumn("ALAMAT");
        tblSupplier.setModel(tb);
        
        try{
            if("search".equals(type)){
                sql = "SELECT * FROM `supplier` WHERE concat(`name`) like '%"+txtSupplierSearch.getText()+"%'";
            }else{
                sql = "SELECT * FROM supplier";
            }
            
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("phone"),
                    rs.getString("address"),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void transactionSupplier(String type){
        if("save".equals(type)){
            if(txtSupplierName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nama Harus diisi!");
            }else if("".equals(txtSupplierPhone.getText())){
                JOptionPane.showMessageDialog(this, "Telepon Harus diisi!");
            }else if("".equals(txtSupplierAddress.getText())){
                JOptionPane.showMessageDialog(this, "Alamat Harus diisi!");
            }else{
                try{
                    sql = "INSERT INTO `supplier` (`name`, `phone`, `address`) VALUES (?,?,?)";
                    pst=con.prepareStatement(sql);
                    pst.setString(1, txtSupplierName.getText());
                    pst.setString(2, txtSupplierPhone.getText());
                    pst.setString(3, txtSupplierAddress.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Supplier Berhasil disimpan.");
                } catch (SQLException err){
                    JOptionPane.showMessageDialog(this, err.getMessage());
                }
            }
        }else if("update".equals(type)){
             if(txtSupplierName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nama Harus diisi!");
            }else if("".equals(txtSupplierPhone.getText())){
                JOptionPane.showMessageDialog(this, "Telepon Harus diisi!");
            }else if("".equals(txtSupplierAddress.getText())){
                JOptionPane.showMessageDialog(this, "Alamat Harus diisi!");
            }else{
                try{
                     sql = "UPDATE `supplier` SET `name` = ?, `phone` = ?, `address` = ? WHERE `supplier`.`id` = ?;";
                    pst=con.prepareStatement(sql);
                    pst.setString(1, txtSupplierName.getText());
                    pst.setString(2, txtSupplierPhone.getText());
                    pst.setString(3, txtSupplierAddress.getText());
                    pst.setString(4, id_supplier);
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Supplier Berhasil di Update");
                } catch(SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }else{
            try{
                sql="DELETE from supplier WHERE supplier.id= ?";
                 pst=con.prepareStatement(sql);
                 pst.setString(1, id_supplier);
                 pst.execute();
                 JOptionPane.showMessageDialog(this, "Data Supplier Berhasil di Hapus"); 
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }
    
    private void clearForm(){
        txtSupplierName.setText(null);
        txtSupplierPhone.setText(null);
        txtSupplierAddress.setText(null);
    }
    
    private void clearVlabel(){
        vSupplierName.setText("-");
        vSupplierPhone.setText("-");
        vSupplierAddress.setText("-");
    }
    
    private void setDefaultBtn(){
        btnSupplierSave.setEnabled(false);
        btnSupplierEdit.setEnabled(false);
        btnSupplierDelete.setEnabled(false);
        txtSupplierName.setEnabled(false);
        txtSupplierPhone.setEnabled(false);
        txtSupplierAddress.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Supplier().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSupplierDelete;
    private javax.swing.JToggleButton btnSupplierEdit;
    private javax.swing.JToggleButton btnSupplierNew;
    private javax.swing.JToggleButton btnSupplierPrint;
    private javax.swing.JToggleButton btnSupplierSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSupplierAddress;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblSupplierPhone;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextArea txtSupplierAddress;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierPhone;
    private javax.swing.JTextField txtSupplierSearch;
    private javax.swing.JLabel vSupplierAddress;
    private javax.swing.JLabel vSupplierName;
    private javax.swing.JLabel vSupplierPhone;
    // End of variables declaration//GEN-END:variables
}
